import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem

def generate_pdf_report(report_data: dict, output_filename: str = "report.pdf") -> str:
    """
    Generates a professional PDF report for deepfake detection results.
    
    Args:
        report_data (dict): A dictionary containing:
            - filename (str)
            - file_type (str)
            - result (str: "Real" or "Fake")
            - confidence (float)
            - risk_level (str)
            - explanation (dict with 'summary' and 'key_indicators' list)
            - timestamp (str)
        output_filename (str, optional): The path to save the PDF. Defaults to "report.pdf".
        
    Returns:
        str: The absolute file path to the generated PDF.
    """
    # Create the full path to guarantee it saves correctly
    filepath = os.path.abspath(output_filename)
    
    # Initialize the Document
    doc = SimpleDocTemplate(
        filepath, 
        pagesize=letter,
        rightMargin=72, 
        leftMargin=72, 
        topMargin=72, 
        bottomMargin=72
    )
    
    # Content flowable array
    elements = []
    
    # Styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = styles['Heading1']
    title_style.alignment = 1 # Center
    title_style.spaceAfter = 20

    heading_style = styles['Heading2']
    heading_style.spaceBefore = 15
    heading_style.spaceAfter = 10
    heading_style.textColor = colors.HexColor("#2C3E50")

    body_style = styles['Normal']
    body_style.fontSize = 10
    body_style.spaceAfter = 8
    
    # Logic for dynamic styling
    is_fake = report_data.get('result', 'Real').lower() == 'fake'
    
    result_style = ParagraphStyle(
        'ResultStyle',
        parent=styles['Normal'],
        fontSize=12,
        fontName='Helvetica-Bold',
        textColor=colors.red if is_fake else colors.green,
        spaceAfter=10
    )

    disclaimer_style = ParagraphStyle(
        'DisclaimerStyle',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.gray,
        alignment=1, # Center
        spaceBefore=30
    )

    # 1. Title
    elements.append(Paragraph("<b>Deepfake Detection Report</b>", title_style))
    
    # 2. Section: Media Information
    elements.append(Paragraph("<b>Media Information</b>", heading_style))
    elements.append(Paragraph(f"<b>Filename:</b> {report_data.get('filename', 'Unknown')}", body_style))
    elements.append(Paragraph(f"<b>File Type:</b> {report_data.get('file_type', 'Unknown').capitalize()}", body_style))
    elements.append(Paragraph(f"<b>Timestamp:</b> {report_data.get('timestamp', 'Unknown')}", body_style))
    elements.append(Spacer(1, 12))

    # 3. Section: Detection Result
    elements.append(Paragraph("<b>Detection Result</b>", heading_style))
    result_text = f"Result: {report_data.get('result', 'Unknown').upper()}"
    elements.append(Paragraph(result_text, result_style))
    elements.append(Paragraph(f"<b>Confidence Score:</b> {report_data.get('confidence', 0.0):.1f}%", body_style))
    elements.append(Spacer(1, 12))

    # 4. Section: Risk Assessment
    elements.append(Paragraph("<b>Risk Assessment</b>", heading_style))
    elements.append(Paragraph(f"<b>Risk Level:</b> {report_data.get('risk_level', 'Unknown')}", body_style))
    elements.append(Spacer(1, 12))

    # 5. Section: Explanation
    elements.append(Paragraph("<b>Explanation</b>", heading_style))
    
    explanation_data = report_data.get('explanation', {})
    summary = explanation_data.get('summary', 'No summary available.')
    elements.append(Paragraph(f"<b>Summary:</b> {summary}", body_style))
    
    indicators = explanation_data.get('key_indicators', [])
    if indicators:
        elements.append(Paragraph("<b>Key Indicators:</b>", body_style))
        list_items = [ListItem(Paragraph(indicator, body_style)) for indicator in indicators]
        elements.append(ListFlowable(list_items, bulletType='bullet', start='circle'))
    
    elements.append(Spacer(1, 20))

    # 6. Footer Disclaimer
    disclaimer_text = "<i>This report is generated by an AI system and should be used for informational purposes only.</i>"
    elements.append(Paragraph(disclaimer_text, disclaimer_style))

    # Build the PDF
    doc.build(elements)
    
    # 4. VALIDATION CHECKS (Debug logs)
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"PDF creation failed, file not found at {filepath}")
        
    file_size_kb = os.path.getsize(filepath) / 1024
    print(f"[DEBUG - PDF Generator] Successfully generated PDF.")
    print(f"[DEBUG - PDF Generator] File Path: {filepath}")
    print(f"[DEBUG - PDF Generator] File Size: {file_size_kb:.2f} KB")
    
    if file_size_kb == 0:
        raise ValueError("Generated PDF is 0 KB (Corrupted/Empty).")
        
    return filepath

if __name__ == "__main__":
    # Test execution
    sample_input = {
      "filename": "sample.mp4",
      "file_type": "video",
      "result": "Fake",
      "confidence": 91.2,
      "risk_level": "High",
      "explanation": {
        "summary": "Detected inconsistencies in facial texture and temporal patterns.",
        "key_indicators": [
          "Frame-to-frame inconsistency",
          "Unnatural facial blending",
          "Lighting mismatch"
        ]
      },
      "timestamp": "2026-03-17 14:30"
    }
    
    output_path = generate_pdf_report(sample_input, "test_report.pdf")
    print(f"Test PDF generated successfully at: {output_path}")
